/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartenariatsRouteImport } from './routes/partenariats'
import { Route as NousSoutenirRouteImport } from './routes/nous-soutenir'
import { Route as NotreMissionRouteImport } from './routes/notre-mission'
import { Route as NosActionsRouteImport } from './routes/nos-actions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComprendreLeDiabeteIndexRouteImport } from './routes/comprendre-le-diabete.index'
import { Route as ComprendreLeDiabeteTopicRouteImport } from './routes/comprendre-le-diabete.$topic'

const PartenariatsRoute = PartenariatsRouteImport.update({
  id: '/partenariats',
  path: '/partenariats',
  getParentRoute: () => rootRouteImport,
} as any)
const NousSoutenirRoute = NousSoutenirRouteImport.update({
  id: '/nous-soutenir',
  path: '/nous-soutenir',
  getParentRoute: () => rootRouteImport,
} as any)
const NotreMissionRoute = NotreMissionRouteImport.update({
  id: '/notre-mission',
  path: '/notre-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const NosActionsRoute = NosActionsRouteImport.update({
  id: '/nos-actions',
  path: '/nos-actions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprendreLeDiabeteIndexRoute =
  ComprendreLeDiabeteIndexRouteImport.update({
    id: '/comprendre-le-diabete/',
    path: '/comprendre-le-diabete/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComprendreLeDiabeteTopicRoute =
  ComprendreLeDiabeteTopicRouteImport.update({
    id: '/comprendre-le-diabete/$topic',
    path: '/comprendre-le-diabete/$topic',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nos-actions': typeof NosActionsRoute
  '/notre-mission': typeof NotreMissionRoute
  '/nous-soutenir': typeof NousSoutenirRoute
  '/partenariats': typeof PartenariatsRoute
  '/comprendre-le-diabete/$topic': typeof ComprendreLeDiabeteTopicRoute
  '/comprendre-le-diabete/': typeof ComprendreLeDiabeteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nos-actions': typeof NosActionsRoute
  '/notre-mission': typeof NotreMissionRoute
  '/nous-soutenir': typeof NousSoutenirRoute
  '/partenariats': typeof PartenariatsRoute
  '/comprendre-le-diabete/$topic': typeof ComprendreLeDiabeteTopicRoute
  '/comprendre-le-diabete': typeof ComprendreLeDiabeteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nos-actions': typeof NosActionsRoute
  '/notre-mission': typeof NotreMissionRoute
  '/nous-soutenir': typeof NousSoutenirRoute
  '/partenariats': typeof PartenariatsRoute
  '/comprendre-le-diabete/$topic': typeof ComprendreLeDiabeteTopicRoute
  '/comprendre-le-diabete/': typeof ComprendreLeDiabeteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/nos-actions'
    | '/notre-mission'
    | '/nous-soutenir'
    | '/partenariats'
    | '/comprendre-le-diabete/$topic'
    | '/comprendre-le-diabete/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/nos-actions'
    | '/notre-mission'
    | '/nous-soutenir'
    | '/partenariats'
    | '/comprendre-le-diabete/$topic'
    | '/comprendre-le-diabete'
  id:
    | '__root__'
    | '/'
    | '/nos-actions'
    | '/notre-mission'
    | '/nous-soutenir'
    | '/partenariats'
    | '/comprendre-le-diabete/$topic'
    | '/comprendre-le-diabete/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NosActionsRoute: typeof NosActionsRoute
  NotreMissionRoute: typeof NotreMissionRoute
  NousSoutenirRoute: typeof NousSoutenirRoute
  PartenariatsRoute: typeof PartenariatsRoute
  ComprendreLeDiabeteTopicRoute: typeof ComprendreLeDiabeteTopicRoute
  ComprendreLeDiabeteIndexRoute: typeof ComprendreLeDiabeteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partenariats': {
      id: '/partenariats'
      path: '/partenariats'
      fullPath: '/partenariats'
      preLoaderRoute: typeof PartenariatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nous-soutenir': {
      id: '/nous-soutenir'
      path: '/nous-soutenir'
      fullPath: '/nous-soutenir'
      preLoaderRoute: typeof NousSoutenirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notre-mission': {
      id: '/notre-mission'
      path: '/notre-mission'
      fullPath: '/notre-mission'
      preLoaderRoute: typeof NotreMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nos-actions': {
      id: '/nos-actions'
      path: '/nos-actions'
      fullPath: '/nos-actions'
      preLoaderRoute: typeof NosActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprendre-le-diabete/': {
      id: '/comprendre-le-diabete/'
      path: '/comprendre-le-diabete'
      fullPath: '/comprendre-le-diabete/'
      preLoaderRoute: typeof ComprendreLeDiabeteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprendre-le-diabete/$topic': {
      id: '/comprendre-le-diabete/$topic'
      path: '/comprendre-le-diabete/$topic'
      fullPath: '/comprendre-le-diabete/$topic'
      preLoaderRoute: typeof ComprendreLeDiabeteTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NosActionsRoute: NosActionsRoute,
  NotreMissionRoute: NotreMissionRoute,
  NousSoutenirRoute: NousSoutenirRoute,
  PartenariatsRoute: PartenariatsRoute,
  ComprendreLeDiabeteTopicRoute: ComprendreLeDiabeteTopicRoute,
  ComprendreLeDiabeteIndexRoute: ComprendreLeDiabeteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
