/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotreMissionRouteImport } from './routes/notre-mission'
import { Route as IndexRouteImport } from './routes/index'

const NotreMissionRoute = NotreMissionRouteImport.update({
  id: '/notre-mission',
  path: '/notre-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notre-mission': typeof NotreMissionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notre-mission': typeof NotreMissionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notre-mission': typeof NotreMissionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notre-mission'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/notre-mission'
  id: '__root__' | '/' | '/notre-mission'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotreMissionRoute: typeof NotreMissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notre-mission': {
      id: '/notre-mission'
      path: '/notre-mission'
      fullPath: '/notre-mission'
      preLoaderRoute: typeof NotreMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotreMissionRoute: NotreMissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
